### ISSUE TITLE
Add scenes 1, 2 and 3 to the build settings

### ISSUE THREAD

**Issue by yeetwenty** [Kecheng-Zhang/COMP3540-Group15-Project#28]
Add Scene 1, Scene 2, and Scene 3 to the build settings by dragging the scenes from the UsedAssets/Scenes folder into the build settings menu found in the 'File' dropdown.

**Comment by SleepyThoughts** [comment]
This has been completed. Scenes 1-3 are in the build settings and transitioning between levels works.
