### ISSUE TITLE
Scene 2 and 3 key and key msg issue

### ISSUE THREAD

**Issue by kechengzhang28** [Kecheng-Zhang/COMP3540-Group15-Project#46]
The keys do not destroy after colliding with the player and the key msg is not displayed.

**Comment by kechengzhang28** [comment]
During countdown, pressing TAB will resume the game

**Comment by yeetwenty** [comment]
I also added countdown in scene 2&3 now scene 2&3 is working well. But do you think it is better with countdown time in scene 2&3 or not?

**Comment by kechengzhang28** [comment]
> I also added countdown in scene 2&3 now scene 2&3 is working well. But do you think it is better with countdown time in scene 2&3 or not?

Either way is good but I think all scenes, 1, 2, 3, should be consistent.

**Comment by yeetwenty** [comment]
okay then I will fix it later ^^

**Comment by kechengzhang28** [comment]
fixed the pause issue
